import requests
from bs4 import BeautifulSoup
import csv
import openpyxl

# Read the URLs and titles from the CSV file generated by the previous code
products = []
with open("amazon_laptops.csv", "r", newline="", encoding="utf-8") as csv_file:
    csv_reader = csv.reader(csv_file)
    next(csv_reader)  # Skip header
    for row in csv_reader:
        if row[1] != "Information not available":  # Check if the URL is valid
            products.append({"Title": row[0], "URL": row[1]})

# Create a new CSV file to write the extracted product details
csv_filename = "product_details.csv"
with open(csv_filename, "w", newline="", encoding="utf-8") as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_headers = ["Title", "Brand", "Model Name", "Screen Size", "Colour", "Hard Disk Size", "CPU Model", "RAM Memory Installed Size", "Operating System"]
    csv_writer.writerow(csv_headers)

    # Create an Excel workbook and sheet
    wb = openpyxl.Workbook()
    sheet = wb.active
    excel_headers = ["Title", "Brand", "Model Name", "Screen Size", "Colour", "Hard Disk Size", "CPU Model", "RAM Memory Installed Size", "Operating System"]
    sheet.append(excel_headers)

    # Iterate through the products and scrape additional information
    for product in products:
        title = product["Title"]
        url = product["URL"]
        HEADERS = {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
        response = requests.get(url,headers=HEADERS)
        soup = BeautifulSoup(response.content, "html.parser")

        # Extract product details
        details_table = soup.find("table", class_="a-normal a-spacing-micro")
        if details_table:
            details = {}
            rows = details_table.find_all("tr")
            for row in rows:
                cells = row.find_all("td")
                if len(cells) == 2:
                    label = cells[0].get_text(strip=True)
                    value = cells[1].get_text(strip=True)
                    details[label] = value

            # Write the extracted data to the CSV file
            csv_writer.writerow([
                title,
                details.get("Brand", "Information not available"),
                details.get("Model Name", "Information not available"),
                details.get("Screen Size", "Information not available"),
                details.get("Colour", "Information not available"),
                details.get("Hard Disk Size", "Information not available"),
                details.get("CPU Model", "Information not available"),
                details.get("RAM Memory Installed Size", "Information not available"),
                details.get("Operating System", "Information not available")
            ])

            # Write the extracted data to the Excel sheet
            sheet.append([
                title,
                details.get("Brand", "Information not available"),
                details.get("Model Name", "Information not available"),
                details.get("Screen Size", "Information not available"),
                details.get("Colour", "Information not available"),
                details.get("Hard Disk Size", "Information not available"),
                details.get("CPU Model", "Information not available"),
                details.get("RAM Memory Installed Size", "Information not available"),
                details.get("Operating System", "Information not available")
            ])

    # Save the Excel file
    wb.save("product_details.xlsx")

print("Product details have been extracted and saved to both product_details.csv and product_details.xlsx")
